### ISSUE TITLE
Desktop firefox

### ISSUE THREAD

**Issue by ImranAhmed** [braintree/browser-detection#11]
Is there a way to detect Firefox on desktop? I couldn't find it in the examples.

**Comment by quinnjn** [comment]
We do not currently have a check for FireFox for non-mobile. Firefox generally doesn't require any extra logic compared to the other browsers, so we've never had a use case to filter logic for Firefox only 😄 

Totally a valid ask though! We would gladly accept a PR to add that!

**Comment by crookedneighbor** [comment]
I'm going to close this for now, since it's not something we require for our SDKs that use this library, but we're happy to review a PR if you'd like to add one.
