### ISSUE TITLE
can you export one bandle files for non treeshakable projects?

### ISSUE THREAD

**Issue by WuglyakBolgoink** [braintree/browser-detection#17]

**Comment by crookedneighbor** [comment]
Can you elaborate on what exactly you're looking for? Are you asking for an already bundled dist file ready for use in the browser? Or something else?

**Comment by WuglyakBolgoink** [comment]
yes.. i will use this plugin on old legacy project... which not supported new technology with imports

**Comment by crookedneighbor** [comment]
We won't be exposing a browser ready bundle for this. This script is primarily consumed by other Braintree projects.

Here's a script that will help you do it yourself. All you need is a current version of node and npm installed.

```bash
npm install @braintree/browser-detection
npx browserify -s browserDetection node_modules/@braintree/browser-detection/browser-detection.js > bundle.js
```

This will create a `bundle.js` file that adds `browserDetection` to the window object.
