### ISSUE TITLE
why is there no isMobile?

### ISSUE THREAD

**Issue by guatedude2** [braintree/browser-detection#37]
It would be great to have a convenient method to check if the device `isMobile`. 

At the moment its a hazel to do that detection with all devices.

cc: @jjlimawapp

**Comment by jplukarski** [comment]
Hello @guatedude2 , thanks for using our browser-detection module. The goal of this library is to check for the specific browser, not just the device. Can you explain your use case for needing to check if it is mobile or not?

In any case, we'll leave this issue open for now to gauge interest in a purely `isMobile` check. Also, feel free to open up a PR and we'll take a look.

**Comment by guatedude2** [comment]
Our use case here is to detect that we’re in a mobile device. We’re trying to show a message that shows only when a user is in a mobile browser. So having to check each individual browser type is a bit of an inconvenience. 

Awesome library btw

**Comment by Noitidart** [comment]
This would be cool. I currently have to rely on `mobile-device-detect` for this.

**Comment by woolrab6** [comment]
Thanks for what you do but be careful with my links please much respect I'm having issues with control over my mobile.

**Comment by hollabaq86** [comment]
Hey folks- thanks again for the feedback. I'm going to close this issue since it's a feature request and not a 🐛, but please know that we are evaluating your request. I don't have an ETA on whether we will add this or when it would be released, so if you really really want this feature feel free to submit a PR!
