### ISSUE TITLE
Fix Edge browser detection

### ISSUE THREAD

**Issue by petercmuc** [braintree/browser-detection#41]
Hey!
I just saw that the detection of Edge browsers fails.
Apparently the user agent strings may either contain **"Edge" OR "Edg"** (see https://developers.whatismybrowser.com/useragents/explore/software_name/edge/). Currently only "Edge" is used in pattern matching, thats why it fails with my current UA of "[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62](https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)"

**Comment by hollabaq86** [comment]
👋 @petercmuc thanks for reaching out and for providing great resources! Yeah this is definitely a bug in our [code](https://github.com/braintree/browser-detection/blob/aaddbcf1decc265a2fb860cf739952158b12904e/src/is-edge.ts#L4), would you like to PR the fix?

If not we can eventually update it, but I don't have an ETA.

**Comment by hollabaq86** [comment]
for internal tracking, ticket 1886

**Comment by petercmuc** [comment]
Hi
I have created a PR for a bug fix:
https://github.com/braintree/browser-detection/pull/42

**Comment by woolrab6** [comment]
Thanks for what you do really thanks.

**Comment by jplukarski** [comment]
This was fixed in v1.17.2. Closing this issue out.
