### ISSUE TITLE
When importing from deep module, types not seen

### ISSUE THREAD

**Issue by Noitidart** [braintree/browser-detection#43]
I am importing just `isIos` like this:

```
import isIos from '@braintree/browser-detection/is-ios';
```

Typescript complains with:

```
Could not find a declaration file for module '@braintree/browser-detection/is-ios'. '/Users/Noitidart/Documents/Test-App/node_modules/@braintree/browser-detection/is-ios.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/braintree__browser-detection` if it exists or add a new declaration (.d.ts) file containing `declare module '@braintree/browser-detection/is-ios';`ts(7016)
```

Is it possible to get `isIos` typed?

What if we make one index file and just do a bunch of `export`, that way it supports tree shaking?

**Comment by hollabaq86** [comment]
👋 @Noitidart thanks for reaching out, we'll take a look and see what we can do.

For internal tracking, issue 700

**Comment by Noitidart** [comment]
Thank you sir for the awesome work and even thought!

**Comment by armandodlvr** [comment]
👋 @Noitidart for TypeScript we recommend importing the module like this `@braintree/browser-detection/dist/is-ios`. This will export the types.

**Comment by Noitidart** [comment]
Oh tank you @armandodlvr that fixed it!
